### ISSUE TITLE
The device options:  bell , bell2 get mixed up and don't display correctly

### ISSUE THREAD

**Issue by sdrapha** [twrecked/lovelace-hass-aarlo#104]
When using more then one doorbell entity/icon, they get mixed up and just one of them shows.

example card:
```yaml
type: custom:aarlo-glance
entity: camera.aarlo_front_door
name: Front Door
image_click: recording
image_view: smart,direct
library_view: smart,download,duration
library_sizes: 3,4,2
image_top: name|status,onoff
image_bottom: motion,library,stream,snapshot,battery,door,bell,bell2|date
door: binary_sensor.front_door_wyze_sensor_2
door_bell: sensor.aarlo_motion_my_doorbell
door2_bell: binary_sensor.aarlo_ding_my_doorbell
```

![image](https://user-images.githubusercontent.com/25059996/127203855-66fe11c6-1167-4e01-871b-88676a4cfe88.png)

Obs: What I really wanted to achieve, is an icon for the doorbell motion, and another for the doorbell pressed. An option to represent this better ( different icon?)  would be awesome.
Thank you for the awesome aarlo component!
