### ISSUE TITLE
Play video from library not working

### ISSUE THREAD

**Issue by gil-c** [twrecked/lovelace-hass-aarlo#106]
Hi,

The video playback is not working properly on my side. The sound works but the image remains like a static preview. I tested on Windows 10 (Chrome and Firefox) and an Android Home Assistant app.

On the other hand the live mode works properly, but only when the camera is disarmed (this is maybe a different problem?).

I have a brand new install of Home Assistant and the Arlo Floodlight Pro 3.

here is my `configuration.yaml`

```
camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

light:
  - platform: aarlo

media_player:
  - platform: aarlo

alarm_control_panel:
  - platform: aarlo
    home_mode_name: disarmed
    away_mode_name: Gilles

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
```

and here is my card configuration:

```
entity: camera.aarlo_jardin
image_click: play
name: Jardin
show:
  - snapshot
  - motion
  - sound
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_date: true
top_status: true
top_title: true
light: light.aarlo_jardin
type: custom:aarlo-glance
```

Is there anything I could try?
