### ISSUE TITLE
Turn camera light on

### ISSUE THREAD

**Issue by ptgomes** [twrecked/lovelace-hass-aarlo#125]
How can I make the camera light switch appear on the card?

**Comment by twrecked** [comment]
Sorry, do we provide a switch for the camera light? (I can't tell from the code and it's been a while since I looked at this stuff.)

**Comment by ptgomes** [comment]
On your code tab you've got:
![image](https://user-images.githubusercontent.com/31014473/197484545-0bc9f815-0971-412d-9d8e-3ff0083261ae.png)

also: _"light; light status, click to turn off and on"_, but the bulb doesn't appear.

**Comment by twrecked** [comment]
You need to add the light id to the card:

```yaml
...
image_bottom:
  - battery,signal,library,sound,motion,stream,snapshot
  - door,lock,bell,light
light: light.porch_light
```
