### ISSUE TITLE
Lock is not showed

### ISSUE THREAD

**Issue by Phoenix-DH** [twrecked/lovelace-hass-aarlo#146]
Hey,

what am I doing wrong.
On the card the lock is not shown:

```
            cards:
              - entity: camera.aarlo_hof
                type: 'custom:aarlo-glance'
                name: Hof
                image_view: arlo-stream
                image_top: 'name,status,door,lock'
                image_bottom: 'motion,library,stream,snapshot,battery'
                image_click: 'recordings'
                library_sizes: '3,4,2'
                door: binary_sensor.werkstatt_tur
                door_lock: lock.nuki_werkstatttur_lock
```

Thanks.
