### ISSUE TITLE
Unable to hide a view

### ISSUE THREAD

**Issue by YpNo** [twrecked/lovelace-hass-aarlo#147]
Hi !

I've tried to disable a view (camera) but it doesn't works.
I tried to hide by the view and the domain but options did nothing.

Here my lovelace raw configuration example:
```yaml
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      camera:
        hidden: true
    extra_views:
      - theme: camera
        title: My Camera
        path: my_cameras
        icon: mdi:cctv
        badgew: []
        cards:
          - type: custom:aarlo-glance
            entity: camera.aarlo_my_camera
            hide:
              - title
              - date
            image_click: stream
            image_view: numeric
            image_bottom: status,motion,sound,library,stream|snapshot,battery
            top_title: false
            top_status: false
            top_date: false
views: []
domains:
   camera:
      hidden: true
```

Thanks for your help
