### ISSUE TITLE
Live stream never gets started

### ISSUE THREAD

**Issue by Phoenix-DH** [twrecked/lovelace-hass-aarlo#153]
Hey folks,

I just read about all the issues here and thought it might be a good one to raise this question after I am now on the way to finalize my config of aarlo.
I love both, but I did not get it managed to get a nearly "live" stream and had the ask f there is any progress on it.

I am using browser_mod.popup within an automation when moving is detected.
The popup will be opened with the right cam, but nothing more is happening.

Did some has a valid config?

Mine looks like the following:
```
dismissable: true
autoclose: false
title: Haustür live
size: normal
timeout: 60000
browser_id:
  - 0fdf7018-e56618fc
content:
  entity: camera.aarlo_haustur
  type: custom:aarlo-glance
  name: Haustür live
  image_view: arlo-stream
  image_top: name,status
  image_bottom: motion,library,stream,snapshot,battery
  image_click: stream
  library_sizes: 3,4,2
  door: binary_sensor.haustur
  door_lock: lock.haustur
```

Thanks.
