### ISSUE TITLE
`global: active` not working

### ISSUE THREAD

**Issue by Wetzel402** [twrecked/lovelace-hass-aarlo#161]
For some reason I can't get the `global: active` configuration to work for my card.  I also don't see any other issues with this.  Here is my configuration:

```
entities:
  - entity: camera.aarlo_front_door
    name: Front Door
    door: binary_sensor.front_door
    light: light.outside_front_lights
  - entity: camera.aarlo_driveway
    name: Driveway
    light: light.outside_front_lights
  - entity: camera.aarlo_backyard
    name: Back Yard
    light: light.outside_deck_lights
  - entity: camera.aarlo_upstairs_living_room
    name: Living Room
    door: binary_sensor.front_door
    door2: binary_sensor.deck_door
    light: light.living_room_lights
  - entity: camera.aarlo_basement_great_room
    name: Basement
    door: binary_sensor.patio_door
    light: light.family_room
global: active,blended
image_top: battery,name|date
image_bottom: previous|library,stream|next
image_view: direct
image_click: recordings
library_sizes: 2,3,4
library_view: duration
door: binary_sensor.front_door
door_lock: lock.front_door_lock
type: custom:aarlo-glance

```

For some reason it always displays `camera.aarlo_basement_great_room` by default. 

Any ideas would be appreciated.

Thanks!
