### ISSUE TITLE
Can't get attributes working :(

### ISSUE THREAD

**Issue by Stupco** [twrecked/lovelace-hass-aarlo#28]
So, just delved into HA for the first time and am deep down the rabbit hole.

I was able to configure Aarlo manually (because of the red warnings when setting up HACS) but was never able to get the lovelace-hass-aarlo working correctly.

As such, now working through HACS and have both Aarlo and this plugin working.

The issue is that none of the attributes are pulling through correctly (such as battery_level and singal_strength, showing up as 0).

My configurations are as follows:
### #configuration.yaml
```
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    
sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
```
### #entity attributes showing as working:
```
access_token: ######
model_name: VMC4030P
brand: Netgear Arlo
battery_level: 76
battery_tech: Rechargeable
brightness: 0
flipped: false
mirrored: false
motion_detection_sensitivity: 80
power_save_mode: best_video
signal_strength: 3
unseen_videos: 0
recent_activity: false
image_source: 'capture/04-28 14:04'
charging: false
charger_type: None
wired: false
wired_only: false
```
### #lovelace card config

```
entity: camera.aarlo_front_door
image_click: play
motion: binary_sensor.aarlo_motion_front_door
name: Front Door
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_date: false
top_status: true
top_title: true
type: 'custom:aarlo-glance'
```
