### ISSUE TITLE
more then 1 camrea

### ISSUE THREAD

**Issue by staticgroup** [twrecked/lovelace-hass-aarlo#34]

**Comment by staticgroup** [comment]
hey mate,
nice integration (im struggling to get working) But thats me, I am struggling in general as I think i have too much squeezed in. I am wondering if you could provide a formatted example for multiplie cameras. 
thanks

Steve

**Comment by twrecked** [comment]
This taken from the raw config editor and is straight out of my test setup. It also includes a glance card with a summary of the alarm states.

```yaml
  - badges: []
    cards:
      - entity: camera.aarlo_front_camera
        name: Front
        show:
          - motion
          - signal_strength
          - snapshot
          - captured_today
          - battery_level
          - play
        top_status: true
        top_title: true
        type: 'custom:aarlo-glance'
      - entity: camera.aarlo_driveway_camera
        name: Front Door
        show:
          - motion
          - signal_strength
          - snapshot
          - captured_today
          - battery_level
          - play
        top_status: true
        top_title: true
        type: 'custom:aarlo-glance'
      - entities:
          - entity: alarm_control_panel.aarlo_front_base
          - entity: alarm_control_panel.aarlo_rear_base
          - entity: alarm_control_panel.aarlo_front_lights
          - entity: alarm_control_panel.aarlo_rear_lights
        title: Bases
        type: glance
      - battery_id: sensor.aarlo_battery_level_front_camera
        entity: camera.aarlo_front_door_camera
        image_click: play
        name: Test
        show:
          - motion
          - sound
          - snapshot
          - battery_level
          - signal_strength
          - captured_today
          - image_date
        top_date: false
        top_status: false
        top_title: false
        type: 'custom:aarlo-glance'
    title: Cameras
```
