### ISSUE TITLE
frontend_latest/chunk.* Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [twrecked/lovelace-hass-aarlo#49]
I have started encountering this error with the Aarlo Glance Card in the latest Home Assistant Beta's.

```txt
Logger: frontend.js.latest.202009070
Source: components/system_log/__init__.py:193
First occurred: 9:21:54 AM (5 occurrences)
Last logged: 9:21:54 AM

https://homeassistant.local/frontend_latest/chunk.92c2eeacab3f441bc0c1.js:2518:2650 Uncaught TypeError: Cannot read property 'split' of undefined
```

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.15.0-115-generic
python_version | 3.8.4
timezone | Europe/London
version | 0.115.0b1
virtualenv | false

Aarlo: 0.7.0-beta.3
Aarlo Glance: 0.1.4.1

Installed via HACS

Example dashboard raw config:

```yaml
      - door_lock: lock.assa_abloy_yale_conexis_l1_sd_l1000_ch_locked
        entity: camera.aarlo_porch
        name: Porch
        show:
          - motion
          - sound
          - battery
          - signal_strength
          - captured
        top_date: true
        top_status: false
        top_title: true
        type: 'custom:aarlo-glance'
```
