### ISSUE TITLE
unable to use aarlo camera

### ISSUE THREAD

**Issue by QuakeGio83** [twrecked/lovelace-hass-aarlo#78]
![Screenshot_20210216-074256_Home Assistant](https://user-images.githubusercontent.com/72661699/108027579-b73b8280-702a-11eb-92c8-ca693571f87d.jpg)

as you can see from attached picture i'm not able to use camera with latest alpha...what i have to do? it is only my issue?

**Comment by twrecked** [comment]
Not good, I must have broke something. Can you try start by trying `CTRL+SHIFT+R` to reload the page.

If that doesn't work, I need to know:
- what browser and OS are you using?
- the card configuration, can you send me a copy
- what language you are using?

Thanks.

**Comment by QuakeGio83** [comment]
I have done CTRL+SHIFT+R on Chrome but I have same issue also on andoird 
app

following my easy configuration (i delated all previous configuration 
just to be sure that i'm starting from clear situation)

entity: camera.aarlo_ingresso
name: Ingresso
image_view: active
image_top: 'name,status'
image_bottom: 'motion,library,play,snapshot,battery'
image_click: 'direct,recordings'
library_view: download
library_sizes: '3,4,2,1'
type: 'custom:aarlo-glance'

let me know if you need more details

**Comment by twrecked** [comment]
That config works here. Did you try opening the devtools then doing the refresh. I think the old card might be cached.

`CTRL+SHIFT+I` then `CTRL+SHIFT+R`

**Comment by QuakeGio83** [comment]
yes, I have done it.

but I have the same issue with Android app and with different browser 
like firefox

look this error details

Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:83
Integration: Stream (documentation, issues)
First occurred: 10:27:44 (1 occurrences)
Last logged: 10:27:44

Error opening stream 
https://arlostreaming95-z1-prod.wowza.arlo.com:80/stream/52M18178BF9B6_1613467658959.mpd?egressToken=1516e81d_9899_4c09_9f76_e8b34807c9ec&userAgent=web&cameraId=52M18178BF9B6_1613467658959&txnId=be!e2d84edb-fd6c-469c-a273-bfeb7e74c39e

**Comment by twrecked** [comment]
Crap. I broke direct streaming, I'll fix that.

**Comment by twrecked** [comment]
```yaml
entity: camera.aarlo_ingresso
name: Ingresso
image_view: 'active,direct'
image_top: 'name,status'
image_bottom: 'motion,library,play,snapshot,battery'
image_click: recordings
library_view: download
library_sizes: '3,4,2,1'
type: 'custom:aarlo-glance'
```

The `direct` was in the wrong place. Does this help?

Can you see the controls and the last image now?
