### ISSUE TITLE
Not all informations are displayed in image bottom

### ISSUE THREAD

**Issue by admeno** [twrecked/lovelace-hass-aarlo#90]
Since version 0.2-alpha.17 not all Icons are displayed in the new view in bottom.
In the old view there is no name, date and Status anymore.

my config for the new View (on_off and the light is not displayed):
```
type: 'custom:aarlo-glance'
entity: camera.aarlo_einfahrt
name: Einfahrt
image_view: direct
image_bottom: 'name,motion,library,snapshot,signal,on_off,sound'
image_click: stream
library_sizes: '3,4,2'
library_view: download
light: light.shelly_shsw_1_483fda82b077
```
![alpha21newView](https://user-images.githubusercontent.com/61088677/109980463-3b1a8d80-7d00-11eb-8b5d-0274611ee665.PNG)

My config for the old view:

```
my config:
entity: camera.aarlo_einfahrt
image_click: play
name: Einfahrt
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date
top_date: false
top_status: false
top_title: false
type: 'custom:aarlo-glance'
```
![alpha21oldview](https://user-images.githubusercontent.com/61088677/109980399-2807bd80-7d00-11eb-8406-d3204e086087.PNG)

**Comment by twrecked** [comment]
With the new config, you need to add everything in you want to see. And I replaced "on_off" with "onoff".
Here is a possibly fixed config:

```yaml
type: 'custom:aarlo-glance'
entity: camera.aarlo_einfahrt
name: Einfahrt
image_view: direct
image_bottom:
  - 'name,motion,library,snapshot,signal,onoff,sound'
  - 'date'
  - 'light'
image_click: stream
library_sizes: '3,4,2'
library_view: download
light: light.shelly_shsw_1_483fda82b077
```

By using the new lines for each `image_bottom` it creates 3 elements on the card and spreads the information about. You could also have used the `|` symbol to do the same:

```yaml
image_bottom: 'name,motion,library,snapshot,signal,onoff,sound|date|light'
```
Or just used commas to spread them out:

```yaml
image_bottom: 'name,motion,library,snapshot,signal,onoff,sound,date,light'
```
