### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by jbdns21** [twrecked/lovelace-hass-aarlo#92]
I am new to Home Assistant and am having trouble figuring out how to add this card to my dashboard. I have aarlo and the Lovelace Hass Aarlo frontend installed via HACS. I’m able to see a picture card for each camera feed but would love to get this much improved card working. Looking at Configuration->Loveless Dashboards->Resources there’s a new JavaScript Module entry “ /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js”. I’ve restarted Home Assistant and cleared my browser data but still do not see an aarlo-glance card. Any help would be greatly appreciated.

**Comment by twrecked** [comment]
There is no custom creation tool; you have to create a `Manual Card`. Try this card but replace the `entity_id` with your camera.

`Triple Dots (Top Right of the screen)` --> `Edit Dashboard` --> `Add Card` --> `Manual Card` then paste in this:

```yaml
entity: camera.aarlo_back_door_camera
name: 'The Back Door'
global: numeric
image_click: 'smart,stream'
image_top: name
image_bottom: 'status,motion,sound,stream,signal,battery,library'
library_click: smart
library_sizes:
  - 2
  - 4
type: 'custom:aarlo-glance'
```
